[package]
name = "__ALGO__"
version = "0.1.0"
edition = "2018"

# The lib name is hard-coded into pipe.rs
[lib]
name = "algorithm"

[dependencies]
algorithmia = { version = "3.0.0-beta", features = ["entrypoint"] }
base64 = "0.5.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
