[package]
name = "algorithmia-pipe"
version = "0.1.0"
edition = "2018"

[dependencies]
algorithmia = { version = "3.0.0-beta.2", features = ["faas"] }
serde = { version = "1.0", features = ["derive"] }
